Upgrades to streamlit app
dlt-hub/dlt pull request #1036
Opened 2024-02-29 16:46 UTC by sultaniman

This PR upgrades our streamlit app #459 which is launched when `dlt pipeline PIPELINE_NAME show` command is called.
It also includes better prompt to detect and install streamlit and additional packages if it is missing.

![image](https://github.com/dlt-hub/dlt/assets/354868/4587b8c6-3a36-4347-b2a8-41259df43c19)

![image](https://github.com/dlt-hub/dlt/assets/354868/40211ac1-4489-49b0-aef8-66b5f04a6987)

2024-02-29 16:52 UTC, sultaniman commented on dlt/cli/helpers/dependencies.py
> +maybe_install_streamlit()
I will remove this and will call it in `streamlit_app/init.py`

2024-02-29 18:00 UTC, rudolfix requested changes
Let's review UI together! First take:
- the sidebar should contain the most important information like pipeline name, destination etc. maybe last load if trace is present
- I do not want to distribute images with the library
- OR we should distribute the streamlit app as dlt extra: we extract this app as seprate dependency

otherwise I'm so happy we are pushing that forward

2024-02-29 18:01 UTC, rudolfix requested changes

2024-02-29 18:01 UTC, rudolfix commented on dlt/cli/helpers/dependencies.py
> +def query_yes_no(question, default="yes"):
what's wrong with current `echo.py` and `clikck` library we use. this should IMO work

2024-03-06 12:19 UTC, sultaniman commented
Closing this in favor of https://github.com/dlt-hub/dlt/pull/1060 because I decided to split automatic dependency installation utilities in the separate PR.

2024-03-06 12:19 UTC, closed without merging