add a script to check wether our poetry lockfile is in order
dlt-hub/dlt pull request #1103
Opened 2024-03-18 13:52 UTC by sh-rp

### Description
Add a script that checks the poetry lockfile for version hashes to ci

2024-03-18 19:35 UTC, rudolfix approved these changes

2024-03-18 19:37 UTC, rudolfix requested changes
this does not work on windows :/ better to parse this in Python

2024-03-19 09:20 UTC, sh-rp commented
@rudolfix alright, done. I have also moved all the  tools to a tools folder (which I like, but you let me know if this is any good). I made sure that check-package still works as intended for the root dir and all above.

2024-03-20 14:40 UTC, rudolfix approved these changes
LGTM!

2024-03-20 14:40 UTC, merged