Pass options to parse iso like strings
dlt-hub/dlt pull request #1219
Opened 2024-04-15 09:27 UTC by VioletM

Now if datetime cannot be parsed by `parse_iso8601` it will be parsed by `_parse_common` with default pendulum options.

2024-04-15 15:18 UTC, rudolfix approved these changes
LGTM! it seems this will also work on pendulum 2.0 so no need to upgrade deps

2024-04-15 15:20 UTC, rudolfix requested changes
just make sure all tests are passing:
https://github.com/dlt-hub/dlt/actions/runs/8686738863/job/23818843284?pr=1219

this function is used to detect dates from strings so run the affected tests

2024-04-16 08:22 UTC, sh-rp commented
@VioletM with this change the function will now detect more datetime objects and you have to update the tests to reflect that. let me know if something is unclear there.

2024-04-17 13:00 UTC, sh-rp approved these changes
looks good :)

2024-04-17 14:07 UTC, merged