Segment Migration: Making Endpoint Configurable.
dlt-hub/dlt pull request #1236
Opened 2024-04-17 14:07 UTC by zem360

### Description
Introducing env variable `RUNTIME__TELEMETRY_ENDPOINT` to overwrite default telemetry endpoint.

### Changes
-  Adding default endpoint to `RunConfiguration`
-  Overwriting default endpoint with `RUNTIME__TELEMETRY_ENDPOINT`.

2024-04-17 15:21 UTC, sh-rp requested changes

2024-04-17 15:21 UTC, sh-rp commented on dlt/common/runtime/segment.py
> +    if "RUNTIME__TELEMETRY_ENDPOINT" not in os.environ:
you do not need to access os.environ, accessing the values in the config is enough. what you need to do here:
* if config.dlthub_telemetry_endpoint is "https://api.segment.io/v1/track", config.dlthub_telemetry_segment_write_key should be provided, if not fail
* if config.dlthub_telemetry_endpoint is None, fail
* if config.dlthub_telemetry_endpoint is something else, it's ok

2024-04-17 15:21 UTC, sh-rp commented on dlt/common/runtime/segment.py
> +    if "RUNTIME__TELEMETRY_ENDPOINT" not in os.environ:
fyi, your environ var does not match the config, so maybe that is the reason for your confusion.

2024-04-17 15:21 UTC, sh-rp commented on dlt/common/runtime/segment.py
> +        if resp.status_code != 200 or resp.status_code != 204:
`if resp.status_code not in [200,204]:`

2024-04-17 15:21 UTC, sh-rp commented on dlt/common/runtime/segment.py
> +        _WRITE_KEY = None
if the checks mentioned above passed, you can just set _SEGMENT_ENDPOINT and _WRITE_KEY to the values form the config at the end

2024-04-17 15:21 UTC, sh-rp commented on dlt/common/runtime/segment.py
> +    if not _WRITE_KEY and _SEGMENT_ENDPOINT != RunConfiguration.dlthub_telemetry_endpoint:
here you can simply check if _SEGMENT_ENDPOINT is None, if so, return. all the other checks where done in the init.

2024-04-18 00:09 UTC, zem360 commented
@sh-rp I messed up the rebase. Need git support

2024-04-18 14:57 UTC, sh-rp approved these changes
this is looking good now @zem360 please create a follow up ticket so we can add some basic tests!

2024-04-23 09:37 UTC, sh-rp approved these changes

2024-04-23 17:29 UTC, merged