Revert tzdata update and update lock
dlt-hub/dlt pull request #1238
Opened 2024-04-17 19:35 UTC by sultaniman

This PR reverts tzdata update in pyproject.toml and updates lockfile.

2024-04-17 20:31 UTC, rudolfix requested changes
@sultaniman please add
1. new label "changes dependencies" that we will add to PRs that change deps
2. explanation to CONTRIBUTING: 
```
### Add / update / remove core library dependencies
```
where you'll explain the process and why we do it!

2024-04-18 10:48 UTC, sh-rp commented on CONTRIBUTING.md
> +### Hypothetical example:
I think we can scrap this section, the above section is clear enough. Also we are not as much concerned about breaking changes (I think) than about other libs our users are using which will collide with our requirements, so in this case we would not enforce a higher minimal version I think. @rudolfix wdyt.

2024-04-18 15:18 UTC, rudolfix requested changes
yeah now it makes sense! @sultaniman @sh-rp should we introduce a label to warns that dependencies are updated? or maybe we add this to the PR template? so you must say if you update core deps or not

@sultaniman you can drop the example

2024-04-18 15:54 UTC, sultaniman commented
@rudolfix @sh-rp I added dependency update label

2024-04-19 08:11 UTC, rudolfix approved these changes
OK! let's merge this and change our PR template - ask about deps changes there

2024-04-19 08:11 UTC, merged