ignores table options on ALTER TABLE
dlt-hub/dlt pull request #1306
Opened 2024-05-01 10:19 UTC by rudolfix

### Description
bigquery destination was raising when table was ALTERed and table options are present. this failed repeated runs of pipelines using `bigquery_adapter` that were migrating schemas.

2024-05-04 22:58 UTC, Pipboyguy requested changes
Nice!

I made one or two comments for your consideration.

2024-05-04 22:58 UTC, Pipboyguy commented on tests/load/bigquery/test_bigquery_table_builder.py
> +    # run sources() again to make sure that table hints are ignored on alter table
Reading this in isolation suggests that the intended behaviour is to not perform the ALTER migration for OPTION hint.

I suggest we leave the original `test_adapter_additional_table_hints_table_description` test and add `test_adapter_additional_table_hints_table_description_with_alter_table` as separate one, with an assert like

```python
assert hints_table.description == "Once upon a time a small table got hinted twice.",
``` 

We can then mark this test as `skip`  until support is added.
Let me know what you think!

2024-05-04 22:58 UTC, Pipboyguy commented on tests/load/bigquery/test_bigquery_table_builder.py
> +        no_hints.with_name(new_name="hints"), table_expiration_datetime="2030-01-01"
Thanks for all these improvements!

2024-05-05 15:14 UTC, rudolfix commented on dlt/destinations/impl/bigquery/bigquery.py
> +            logger.info(
I considered that. but unfortunately this is a "normal" behavior - ie you declare a table with a description and then you'll get a warning each time the schema is updated. we'd need to check if the description is there - and if it isn't we could issue a warning. but this is out of scope of the ticket - I just want to fix a bug

2024-05-05 16:41 UTC, Pipboyguy commented on dlt/destinations/impl/bigquery/bigquery.py
> +            logger.info(
cool makes sense

2024-05-08 16:11 UTC, Pipboyguy approved these changes

2024-05-08 20:08 UTC, merged