Docs update on how to use ODBC credentials in sql database
dlt-hub/dlt pull request #1309
Opened 2024-05-02 11:18 UTC by dat-a-man

### Description
Docs update on how to use ODBC credentials in sql database

<!--
Please link any related issues. This helps us keep the PR focused and merge it faster.
None

2024-05-08 11:52 UTC, AstrakhantsevaAA approved these changes

2024-05-08 12:38 UTC, AstrakhantsevaAA approved these changes

2024-05-08 19:54 UTC, rudolfix requested changes

2024-05-08 19:54 UTC, rudolfix commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
>     sources.sql_database.credentials="mssql://user:pw@my_host/my_database?trusted_connection=yes"
this looks wrong. user and password should not be specified. also the dialect is missing from scheme.
https://stackoverflow.com/questions/24085352/how-do-i-connect-to-sql-server-via-sqlalchemy-using-windows-authentication
```
from sqlalchemy import create_engine

server = <your_server_name>

database = <your_database_name>

engine = create_engine('mssql+pyodbc://' + server + '/' + database + '?trusted_connection=yes&driver=ODBC+Driver+17+for+SQL+Server')
```
```

2024-05-08 19:54 UTC, rudolfix commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +1. To pass credentials with ODBC driver, you can modify your connection string as:
@dat-a-man what this adds on top of the examples above? is this alternative to the windows authentication?
maybe we could refer to this documentation? https://dlthub.com/docs/dlt-ecosystem/destinations/mssql#setup-guide
I compiled the most common problems from our users (mostly SSL, certificates)

2024-05-09 05:55 UTC, dat-a-man commented
Thanks for reviewing Marcin, yes your documentation covers this [here](https://dlthub.com/docs/dlt-ecosystem/destinations/mssql#setup-guide). So this additiong is not required and can be closed. 

Sorry, I missed it earlier. 
I'll close this PR now.

2024-05-09 05:55 UTC, closed without merging