ability to add partitions in Athena to resources
dlt-hub/dlt pull request #1349
Opened 2024-05-13 08:45 UTC by Vitalii0-o

dlt version
0.4.10

Describe the problem
[Athena code](https://github.com/dlt-hub/dlt/blob/devel/dlt/destinations/impl/athena/athena.py#L358) there is no way to add partitions for Athena tables

Expected behavior
Added the ability to partition Athena tables in a schema

Steps to reproduce
try to create a partitioned table in Athena

Operating system
Linux

Runtime environment
Airflow

Python version
3.11

dlt data source
No response

dlt destination
AWS Athena / Glue Catalog

Other deployment details
No response

Additional information
No response

2024-05-13 10:05 UTC, sh-rp requested changes
Thanks for the contribution :)
We need:
* Move to adapter (see comment)
* A test for creating a table with partitions
* A test for adding a partition to an existing table
* A small update in the athena docs about the partitions (see how it is done bigquery)

2024-05-13 10:05 UTC, sh-rp commented on dlt/common/schema/typing.py
> +    partition: Optional[bool]
Please have a look at how we add partitions in bigquery with the bigquery adapter, it's very easy to do and you can copy most of the code from there probably.

2024-05-21 07:32 UTC, nicor88 commented
Few comments from my side, because there is something missing:
* Adding partitions for external tables (hive) without having dlt writing to the right partitioning schema in s3 is not enough. The data in S3 must match the partitions schema defined - you should add some example on how we you can leverage the s3 layout: `"{table_name}/{test-params}/{YYYY}-{MM}-{DD}/{load_id}.{file_id}.{ext}"` in this case the partition can be called for example `extaction_date` . Also, after dlt writes to s3 you should add the partition to the table via a metadata call, for example `ALTER TABLE elb_logs_raw_native_part ADD PARTITION (dt='2015-01-01') location 's3://athena-examples-us-west-1/elb/plaintext/2015/01/01/'.` - on the first run you can leverage `MSCK REPAIR TABLE impressions`, but for incremental runs this operation is too expensive.
* You should add also partitioning for iceberg tables, in that case the writer is athena itself, not dlt, so what you proposed for hive/external tables should be enough.


Not sure if dlt has integration tests available to run, but you should add integrations tests to verify that the result of adding data to a partitioned table is correct - @sh-rp can for sure help you out here.

2024-05-22 17:46 UTC, rudolfix commented
@nicor88 yes we have end to end test and we can test the layout. ideally we could somehow test this via some SQL command. we'll put you as a reviewer here. OK?

2024-05-24 09:38 UTC, rudolfix commented
@Vitalii0-o we are moving to #1403

2024-05-24 09:38 UTC, closed without merging

2024-05-24 11:27 UTC, nicor88 commented
@rudolfix 
>also when looking at the documentation: if I use ADD PARTITION and LOCATION I can have any file layout I want. I just need to provide a file name to LOCATION and that's it, right?
In theory yes, pratically it's a bad practises, because we introduce inconsistency between the S3 layout and the partition definition, and on scale could slow the engine down.

Also, feel free to add me anywhere or ping me when necessary :) happy to help.