Updated Filesystem Documentation: Handling Deeply Nested JSON
dlt-hub/dlt pull request #1385
Opened 2024-05-20 04:59 UTC by dat-a-man

This PR updates the filesystem documentation to include instructions for handling deeply nested JSON files by enabling automatic directory creation.
Changes:

Documentation Update:
- Provided instructions for setting kwargs = '{"auto_mkdir": true}' in config.toml.
- Included steps for setting kwargs using environment variables.

2024-05-24 10:52 UTC, VioletM requested changes

2024-05-24 10:52 UTC, VioletM commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +To set using environment variables:
Let's move this to the tip above (line 362)

2024-05-24 10:52 UTC, VioletM commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +# for deeply nested layouts
```suggestion
# for automatic directory creation in the local filesystem
```

2024-05-24 11:20 UTC, dat-a-man commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +# for deeply nested layouts
updated

2024-05-27 09:13 UTC, AstrakhantsevaAA commented
@dat-a-man, you trying to merge changes from master to devel, you don;'t need to do that. Which branch did your branch originate from master or devel?

2024-05-27 11:25 UTC, closed without merging