Fix: ensure custom session can be provided to rest client
dlt-hub/dlt pull request #1396
Opened 2024-05-22 03:20 UTC by z3z1ma

### Description

A simple fix for a small oversight in the rest client. Additionally a test proving you can pass a custom session and there is no crash.

### Related Issues

- Fixes #1395

### Additional Context

2024-05-22 03:54 UTC, z3z1ma commented
This is also confusing
https://github.com/dlt-hub/dlt/blob/64c953816c99643e1b6569f5b1fcba12dcc8de2b/dlt/sources/helpers/rest_client/client.py#L186-L190

Why is this there is raise for status is intended to be configured at session level

2024-05-22 03:58 UTC, z3z1ma commented
Also note, you bypass `session.request` though this code path here
https://github.com/dlt-hub/dlt/blob/64c953816c99643e1b6569f5b1fcba12dcc8de2b/dlt/sources/helpers/rest_client/client.py#L92-L133


And call `session.send` directly BUT there is no retry logic on `send`. Its only monkey-patched into `session.request` here
https://github.com/dlt-hub/dlt/blob/64c953816c99643e1b6569f5b1fcba12dcc8de2b/dlt/sources/helpers/requests/retry.py#L242 

I can fix that too.

2024-05-22 09:20 UTC, burnash commented
> you bypass session.request though this code path here

Yes, very good catch! Thanks for the fix again.

> This is also confusing
> ```
> def raise_for_status(response: Response, *args: Any, **kwargs: Any) -> None: 
>     response.raise_for_status() 
> if "response" not in hooks: 
>     hooks["response"] = [raise_for_status]
> ```

Agreed, not the most elegant solution, the idea is to enable hooks while having the rase_for_status as a default. This is also related to the session check. I wanted to give the user a way to override the default behaviour. Naturally the suggestions of how to do this better are very welcome!

2024-05-22 09:24 UTC, rudolfix approved these changes
LGTM!

one question: are you trying to use a session that is not from `requests` library? ie `httpx`?

2024-05-22 09:26 UTC, rudolfix requested changes
I think that your change somehow broke one test where I expect the host is mocked.
```
FAILED tests/sources/helpers/rest_client/test_client.py::TestRESTClient::test_oauth_jwt_auth_success - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08d16f1710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
@z3z1ma pls ping us if you have time to investigate that soon, otherwise we'll take over

2024-05-23 00:37 UTC, z3z1ma commented
Test is passing for me 🤔  interesting, it shouldnt be flaky?

![image](https://github.com/dlt-hub/dlt/assets/41213451/a75a0c43-2014-4964-87a8-7742ad7f38d0)



Also was doing my PR reply using https://github.com/pwntester/octo.nvim and totally replied via appending/editing your comments by accident (didnt even know that was possible)

2024-05-23 00:39 UTC, z3z1ma commented
> LGTM!
> 
> one question: are you trying to use a session that is not from `requests` library? ie `httpx`?

Actually I was trying to use the dlt requests Client.session (I had done some custom stuff but wanted the default retry logic).


> Agreed, not the most elegant solution, the idea is to enable hooks while having the raise_for_status as a default. This is also related to the session check. I wanted to give the user a way to override the default behaviour. Naturally the suggestions of how to do this better are very welcome!

Would it make more sense to inherit from the session by default? This way the behavior is consistent within a source but can still be overridden on a per endpoint basis? I need to double check if/how sessions exposes this.

2024-05-23 00:39 UTC, z3z1ma commented on dlt/sources/helpers/rest_client/client.py
> -        # has raise_for_status=True by default
Ok re-added

2024-05-23 00:40 UTC, z3z1ma commented on dlt/sources/helpers/rest_client/client.py
> +            self.session = _warn_session_raise_for_status(session)
Ok will update the function name to `_warn_and_return` along those lines

2024-05-23 08:48 UTC, burnash commented on dlt/sources/helpers/rest_client/client.py
> +def _warn_session_raise_for_status(session: BaseSession) -> BaseSession:
Thanks for elaborating! Agreed.

2024-05-23 17:15 UTC, burnash commented
> Would it make more sense to inherit from the session by default? This way the behavior is consistent within a source but can still be overridden on a per endpoint basis? I need to double check if/how sessions exposes this.

Yeah I was also contemplating this. But in that case how do we allow the user to pass their own Session?

2024-05-23 18:07 UTC, burnash commented
> Test is passing for me 🤔 interesting, it shouldnt be flaky?

I've checked out the branch locally and also don't see this test_oauth_jwt_auth_success error. 🤔

2024-05-24 13:57 UTC, burnash commented
> this is due to the OAuthAuth using default dlt session which is created before the mock by some other test... let me take a look and fix it

Interesting

2024-05-27 12:52 UTC, burnash approved these changes
Looks good, @z3z1ma! Thanks for fixing it!

2024-05-27 18:40 UTC, merged