1272 Support ClickHouse GCS S3 compatibility mode in filesystem destination
dlt-hub/dlt pull request #1423
Opened 2024-05-28 18:19 UTC by Pipboyguy

### Description

Updates the filesystem destination to support using the S3 implementation with GCS buckets that have S3 interoperability mode (HMAC keys) enabled. 

Key changes:
- Update `convert_storage_to_http_scheme` utility function to properly handle GCS endpoints
- Modify ClickHouse load job to raise an exception if GCS bucket is used without providing S3 compatible credentials (access key ID and secret access key)
- Add test case to verify ClickHouse loading from GCS bucket using S3 compatibility mode
- Remove old gcs tests. These will be added back in when named destinations are supported in templated tests.

### Related Issues

- Resolves #1181
- Fixes #1272

2024-05-29 21:24 UTC, rudolfix requested changes
code: LGTM!
@Pipboyguy do we have the right credentials in our CI so this test is really connecting to clickhouse?

@sh-rp you should review this

2024-05-30 09:03 UTC, sh-rp commented on docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
> +### Using S3-Compatible Storage as a Staging Area
maybe mention google cloud storage in the title here too

2024-05-30 09:05 UTC, sh-rp commented on tests/load/clickhouse/test_clickhouse_gcs_s3_compatibility.py
> +def test_clickhouse_gcs_s3_compatibility() -> None:
looks good!

2024-05-30 09:07 UTC, sh-rp commented
> code: LGTM! @Pipboyguy do we have the right credentials in our CI so this test is really connecting to clickhouse?
> 
Yeah I put those in yesterday. The question you were asking was wether it is really connecting to GCS, right?

2024-05-30 13:18 UTC, Pipboyguy commented
> code: LGTM! @Pipboyguy do we have the right credentials in our CI so this test is really connecting to clickhouse?
> 
> @sh-rp you should review this

@rudolfix  We are indeed connecting to GCS with HMAC credentials and [test passes](https://github.com/dlt-hub/dlt/actions/runs/9285866234/job/25551337483?pr=1423#step:8:43)

2024-06-03 10:16 UTC, merged