feat/1495 rest_client: renames JSONResponsePaginator to JSONLinkPaginator
dlt-hub/dlt pull request #1558
Opened 2024-07-08 10:05 UTC by willi-mueller

### Description

Implements: https://github.com/dlt-hub/dlt/issues/1495

### Related Issues
-

2024-07-08 13:26 UTC, rudolfix requested changes
Looks good but this is a breaking change so what we need is
- JSONResponsePaginator as an alias or derive it directly from `JSONLinkPaginator`
- deprecate it, I think you can deprecate classes

what are you planning to do with `rest_api`? will it continue to work with old `dlt` or you will bump the required version?

2024-07-08 14:34 UTC, burnash commented
@willi-mueller Looks good, I agree with @rudolfix we need to deprecate JSONResponsePaginator,

@rudolfix will something like this work?

```python
import warnings

class JSONLinkPaginator(BaseNextUrlPaginator):
    ...


class JSONResponsePaginator(JSONLinkPaginator):
    def __init__(self):
        warnings.warn("JSONResponsePaginator is deprecated and will be removed in version 1.0.0. Use JSONLinkPaginator instead.", DeprecationWarning, stacklevel=2)
        super().__init__()
```

2024-07-08 14:35 UTC, burnash requested changes
Great work, let's also deprecate the old class. See the comment above.

2024-07-08 16:54 UTC, willi-mueller commented
> Great work, let's also deprecate the old class. See the comment above.

Thanks! I marked the old class as deprecated and rebased onto devel.

2024-07-11 12:43 UTC, burnash commented on docs/website/docs/general-usage/http/overview.md
>      data_selector="results",                                 # (2)
```suggestion
    data_selector="results",                             # (2)
```

2024-07-11 12:45 UTC, burnash approved these changes
Looks good! Thank you @willi-mueller

2024-07-18 21:11 UTC, merged