Add clarification for add_limit
dlt-hub/dlt pull request #1594
Opened 2024-07-15 11:40 UTC by VioletM

Docs were confusing about whether the number of records is limited.

Closes https://github.com/orgs/dlt-hub/projects/11?pane=issue&itemId=70933002

2024-07-15 18:11 UTC, rudolfix requested changes
@VioletM are you able to review docstring as well? we have `add_limit` method on `DltSource` and `DltResource`

2024-07-16 09:39 UTC, AstrakhantsevaAA reviewed
Very good!

2024-07-16 09:39 UTC, AstrakhantsevaAA commented on docs/website/docs/general-usage/source.md
> +Note that `add_limit` **does not limit the number of records** but rather the "number of yields". dlt will close the iterator/generator that produces data after the limit is reached.
```suggestion
Note that `add_limit` **does not limit the number of records** but rather the "number of yields". `dlt` will close the iterator/generator that produces data after the limit is reached.
```

2024-07-16 09:39 UTC, AstrakhantsevaAA submitted a review, later dismissed

2024-07-16 13:40 UTC, AstrakhantsevaAA approved these changes

2024-07-29 09:40 UTC, rudolfix approved these changes

2024-07-29 09:40 UTC, merged