add docs
dlt-hub/dlt pull request #162
Opened 2023-02-28 17:03 UTC by adrianbr

2023-02-28 17:21 UTC, rudolfix requested changes
1. this is better than what we have now :)
2. in glossary we should define terms and provide examples, not the instructions how to write those
3. it looks like a General Usage page - there's one already written in the technical docs. should we rather add a new page and work together to merge this with the other information there?

2023-02-28 17:21 UTC, rudolfix commented on docs/website/docs/glossary.md
> +A dlt Source is the code that handles getting data from an api.
what about google sheet, sql, jsonl and many other sources that are not APIs?

2023-02-28 17:21 UTC, rudolfix commented on docs/website/docs/glossary.md
> +A pipeline’s unique identifier is the name. If no name is given, then the pipeline takes the name of the source or generator you pass to it.
it takes the default name from the currently executing module. all the defaults are explained in the general usage documentation and in docstrings

2023-02-28 19:22 UTC, TyDunn requested changes
Nice work! I agree we need more explanations of these key parts of `dlt`. However, I think the glossary should just be for 1-2 sentence definitions. I recommend that we create a new sidebar item `Concepts` and then add these three deep explanations there. The specific details look pretty good, so assuming you get approval from Marcin and make the structural changes I am requesting, I think you can merge. There are small style things that we can clean up over time. Most important is to get this info shipped and iterate quickly on it

2023-03-01 10:26 UTC, adrianbr commented
> 1. this is better than what we have now :)
> 2. in glossary we should define terms and provide examples, not the instructions how to write those
> 3. it looks like a General Usage page - there's one already written in the technical docs. should we rather add a new page and work together to merge this with the other information there?

I am not sure either.

2023-03-01 10:33 UTC, adrianbr commented
> 1. this is better than what we have now :)
> 2. in glossary we should define terms and provide examples, not the instructions how to write those
> 3. it looks like a General Usage page - there's one already written in the technical docs. should we rather add a new page and work together to merge this with the other information there?

Going through the general usage, it is very hard to comprehend - why am i reading, what problem am i trying to solve? I will not remember that I can find information in this because it's just a dump of many things. Perhaps general usage will be recycled into in-detail pages about the concepts?

2023-03-01 14:28 UTC, merged