Add custom parent-child relationships example
dlt-hub/dlt pull request #1678
Opened 2024-08-10 06:52 UTC by dat-a-man

### Description

Added example to load parent table keys into child table records.

issue- #1589

2024-08-15 09:12 UTC, VioletM requested changes

2024-08-15 09:12 UTC, VioletM commented on docs/examples/parent_child_relationship/parent_child_relationship.py
> +ensuring that we can use self-defined parent keys in the child table.
```suggestion
This example demonstrates handling data with parent-child relationships using the `dlt` library. You learn how to integrate specific fields (e.g., primary, foreign keys) from a parent record into each child record.
```

2024-08-15 09:12 UTC, VioletM commented on docs/examples/parent_child_relationship/parent_child_relationship.py
> +- Integrate a custom `parent_id` into each child record.
too much chat-gpt 

```suggestion
- Add `parent_id` into each child record using `add_parent_id` function
- Use the [`add_map` function](https://dlthub.com/docs/api_reference/extract/resource#add_map) to apply this
custom logic to every record in the dataset
```

2024-08-16 03:49 UTC, dat-a-man commented on docs/examples/parent_child_relationship/parent_child_relationship.py
> +ensuring that we can use self-defined parent keys in the child table.
done

2024-08-16 03:49 UTC, dat-a-man commented on docs/examples/parent_child_relationship/parent_child_relationship.py
> +- Integrate a custom `parent_id` into each child record.
done

2024-08-23 13:37 UTC, VioletM approved these changes

2024-08-23 14:33 UTC, merged