1672 - moves filesystem source
dlt-hub/dlt pull request #1732
Opened 2024-08-22 20:22 UTC by rudolfix

### Description
1. keeps example pipelines and runs them in tests
2. places tests in tests/load/sources/ because they depend on bucket configs that are available in load
3. uses existing util functions and fixtures

2024-08-23 08:20 UTC, sh-rp commented on tests/load/sources/filesystem/test_filesystem_source.py
> +@pytest.mark.parametrize(
with this setup you'll always run the example pipeline against duckdb, not against the currently active destination. I'm not quite sure how to inject the right destination for this test, maybe in the future we can make use of the updated dlt init command that is run before the tests to create a file with the right destination from which we can import this, not sure.

 I'd also suggest at least doing a very basic inspection of the loaded data by attaching to the pipeline, but maybe this is not needed..

2024-08-23 08:24 UTC, sh-rp requested changes
To me it looks good with 2 questions:
* How do we test against all destinations properly (see comment below)
* Where do we specify the needed dependencies for the example pipeline (I will figure this out in my init PR, as suggested in slack I think I would rather use a templates folder that can contain all of this)

2024-08-23 09:26 UTC, rudolfix commented
> How do we test against all destinations properly (see comment below)
Right, I forgot about it. The tests are placed in `tests/load` so I'd just add our standard destination config parametrize to it. And they will be picked up automatically,

The example tests - they should run only on duckdb and local filesystem. And I will move them back to tests/sources

> Where do we specify the needed dependencies for the example pipeline (I will figure this out in my init PR, as suggested in slack I think I would rather use a templates folder that can contain all of this)
filesystem does not have additional requirements. I'd probably keep them together with the code as in verified sources. best if you propose something neat :)

2024-08-23 10:07 UTC, sh-rp approved these changes

2024-08-29 11:42 UTC, VioletM commented on dlt/sources/filesystem/readers.py
> +def _read_jsonl(items: Iterator[FileItemDict], chunksize: int = 1000) -> Iterator[TDataItems]:
@rudolfix 
I'd suggest adding another reader for `.json` files. It's quite easy and it's being requested from time to time.

2024-09-03 09:21 UTC, merged