Feat/1749 abort load package and raise exception on terminal errors in jobs
dlt-hub/dlt pull request #1781
Opened 2024-09-03 11:57 UTC by willi-mueller

### Description

### Related Issues

- Implements first part of #1749

2024-09-03 13:51 UTC, rudolfix requested changes
How we need to test it
1. there are tests in dummy client that are testing abort feature, there just remove the flag. it is by default on
2. make the other tests to pass by disabling the flag

look for `raise_on_failed_jobs` in the whole code
we use it to raise on load info, those are not needed anymore and can be removed (many of those)

I see that we set this flag in airflow helper. we should change the default there and also we never set it to false

there are other cases. you'll find them for sure

2024-09-03 13:51 UTC, rudolfix commented on docs/website/docs/running-in-production/running.md
> +# you should really load just one job at a time to get the deterministic behavior
let's remove workers=1 thing

2024-09-09 08:00 UTC, willi-mueller commented on docs/website/docs/running-in-production/running.md
> +# you should really load just one job at a time to get the deterministic behavior
Done

2024-09-09 08:16 UTC, willi-mueller commented on docs/website/docs/running-in-production/running.md
> +# you should really load just one job at a time to get the deterministic behavior
Done

2024-09-09 08:21 UTC, willi-mueller commented on docs/website/docs/reference/performance_snippets/performance-snippets.py
> +        # results contains two LoadInfo instances
Without the references into the `results` list this example is less instructive. I am not sure whether to:
1. leave only the comment
2. leave the calls to `results[n].raise_on_failed_jobs()`
3. call some other method/property, e.g. print(results[0]) or `results[0].asdict()`

2024-09-09 08:30 UTC, willi-mueller commented on dlt/helpers/airflow_helper.py
> +        inconsistent state. See https://dlthub.com/docs/running-in-production/running#handle-exceptions-failed-jobs-and-retry-the-pipeline.
Setting the destination to an inconsistent state sounds scary. However, it's a necessary inconvenience, correct?

2024-09-09 15:42 UTC, willi-mueller commented on tests/pipeline/test_pipeline.py
> +    os.environ["RAISE_ON_FAILED_JOBS"] = "true"  # TODO: why is this necessary?
Without setting this env, the pipeline does not raise. However, it should be the default. Thus, the implementation must be incomplete.

2024-09-09 21:35 UTC, rudolfix approved these changes
LGTM!

2024-09-10 13:34 UTC, merged