Support Spatial Types for PostGIS
dlt-hub/dlt pull request #1927
Opened 2024-10-04 13:27 UTC by Pipboyguy

### Description
This PR adds support for PostGIS GEOMETRY type in PostgreSQL. It introduces a logical type for GEOMETRY on binary or text fields.

Users can declare geometry columns via the postgres_adapter, enabling direct insertion of WKT and WKB representations, in addition to GeoPandas integration with automatic geometry column detection and conversion.

### Related Issues

- Closes #696

2024-11-01 16:30 UTC, burnash commented on dlt/destinations/impl/postgres/postgres.py
> +                f"COPY {qualified_table_name} ({headers}) FROM STDIN WITH (FORMAT CSV, DELIMITER"
👍

2024-11-01 16:59 UTC, burnash commented on tests/load/cases/loading/sample_geodata.xml
Is this file being used somewhere? (maybe implicitly?) I can't find the reference to it.

2024-11-01 17:00 UTC, burnash reviewed
Thanks for the PR, @Pipboyguy 
I have a couple of questions, please see my comments.

2024-11-02 17:18 UTC, Pipboyguy commented on tests/load/cases/loading/sample_geodata.xml
It isn't anymore, I wanted to use it for geopandas tests but ended up forgetting abuot it. Thanks for catching this! Removed

2024-11-06 15:26 UTC, Pipboyguy commented on dlt/destinations/impl/postgres/postgres.py
> +    def _split_fragment_to_records(text: str) -> List[str]:
@burnash I looked into it and I don't believe there would be much benefit from bringing in sqlparse as a dependency. Looking at the docs, there's nothing to handle the complex nested parentheses needed for geometry type parsing like `ST_GeomFromText('POINT(1 1)')`. 

The only parentheses handling shown is the basic [`Parenthesis` ](https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Parenthesis)token class, which can't distinguish between the outer VALUES parentheses and nested geometry function calls. The nested brackets would make the control flow just as complex as our current parser, if not more so when handling PostGIS-specific syntax. 

Thoughts?

2024-11-25 22:18 UTC, rudolfix requested changes
this is really good!
1. my suggestion is that we drop wkb and just keep wkb_text. also move shapely to dev dependencies
2. IMO csv with WKT and WKB_HEX should work! did you try it? it'd be hard to understand why not....

2024-11-25 22:18 UTC, rudolfix commented on dlt/common/data_writers/escape.py
> +        if is_valid_wkb(v):
this is very impractical :/ we have a dependence on shapely and there may be false positives (there are no magic numbers in wkb). passing expected type to escape...literal will slow this down

we could use a special binary type but user would need to wrap binary anyway. so my take is to drop `wkb` and just keep `wkb_hex`.

2024-11-26 19:03 UTC, Pipboyguy commented on tests/load/postgres/utils.py
> +from shapely.wkb import dumps as wkb_dumps  # type: ignore
Yes, it is used in `load.postgres.test_postgres_table_builder.test_geometry_types` to generate valid geometries. This should probably be a changed to a fixture if we use it again

2024-11-26 19:29 UTC, Pipboyguy commented on dlt/destinations/impl/postgres/postgres.py
> +            raise TerminalValueError(
I added csv loader cases to the geo test, and it all passes. Your intuition was entirely correct!

2024-11-30 19:24 UTC, rudolfix approved these changes
LGTM!

2024-11-30 19:26 UTC, merged