dcAdded partial loading example for file system
dlt-hub/dlt pull request #1955
Opened 2024-10-15 10:01 UTC by dat-a-man

### Description

In this example, a Python script interacts with the Chess.com REST API to extract game data for a specific user on a 
monthly basis. The script retrieves game data for a specified time range, and when additional data is loaded for a 
different time range, it automatically handles de-duplication by deleting any previously loaded files for overlapping time range.

2024-10-18 17:08 UTC, AstrakhantsevaAA reviewed
@dat-a-man Add please `bucket_url` to config.toml and set it up

2024-10-18 17:12 UTC, AstrakhantsevaAA requested changes

2024-10-18 17:12 UTC, AstrakhantsevaAA commented on docs/examples/partial_loading/partial_loading.py
> +- How to configure a [REST API source](../general-usage/rest_api_source) using the `dlt` library.
fix link: /docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md

2024-10-18 17:12 UTC, AstrakhantsevaAA commented on docs/examples/partial_loading/partial_loading.py
> +- How to use [Filesystem](../general-usage/filesystem_destination) as a destination for storing extracted data.
fix link

2024-10-21 12:11 UTC, dat-a-man commented on docs/examples/partial_loading/partial_loading.py
> +- How to configure a [REST API source](../general-usage/rest_api_source) using the `dlt` library.
updated

2024-10-21 12:23 UTC, dat-a-man commented on docs/examples/partial_loading/partial_loading.py
> +- How to use [Filesystem](../general-usage/filesystem_destination) as a destination for storing extracted data.
updated

2024-10-22 08:20 UTC, AstrakhantsevaAA commented
@dat-a-man Add please bucket_url to config.toml and set it up

2024-11-05 04:16 UTC, closed without merging

2024-11-05 04:17 UTC, dat-a-man commented
Closed as per discussion with Alena.