Excludes examples from mypy and flake8 checks in Makefile
dlt-hub/dlt pull request #1969
Opened 2024-10-21 12:37 UTC by burnash

2024-10-28 10:01 UTC, sh-rp approved these changes

2024-10-29 08:56 UTC, rudolfix requested changes
why we disable mypy and flake? there are several serious issues that it detects.
if you want untyped code allow Any in signatures and returns. this can be done in mypy.ini (per folder)

same for flake

2024-11-01 15:05 UTC, burnash commented
@rudolfix we're not disabling it, the PR removes checking `docs/example` twice in a row

2024-11-01 16:53 UTC, rudolfix approved these changes
LGTM!

2024-11-01 16:53 UTC, merged