post run introspection
dlt-hub/dlt pull request #199
Opened 2023-03-22 17:36 UTC by rudolfix

closes #134 
closes #50 
closes #184

2023-03-29 16:12 UTC, TyDunn approved these changes
Docs look good now. Monster PR! 👹

2023-03-29 18:45 UTC, burnash requested changes
Nice work on the PR! I noticed a few issues and I'll take a closer look tomorrow and give you more detailed feedback.

2023-03-29 19:16 UTC, burnash commented on dlt/common/runtime/slack.py
> +    """Sends a `message` to  Slack `incoming_hook`, by default formatted as markdown. Returns http status code"""
The docstring mentions that the function returns the HTTP status code, but the function is defined to return None.

2023-03-29 19:24 UTC, burnash commented on dlt/common/runtime/slack.py
> +        data= json.dumps({
There's an extra space between = and json. flake8 is likely not strict enough ;)

2023-03-30 11:18 UTC, rudolfix commented on dlt/cli/pipeline_command.py
> +            if len(failed_jobs) > 0:
you are right. and I just learned that you can have `else` for `for` loop
https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops

2023-03-30 11:18 UTC, rudolfix commented on dlt/cli/pipeline_command.py
> +                    fmt.echo("No failed jobs found")
you are right. and I just learned that you can have `else` for `for` loop
https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops

2023-03-30 22:26 UTC, merged