Strapi setup guide
dlt-hub/dlt pull request #212
Opened 2023-03-29 13:34 UTC by TyDunn

2023-03-29 15:15 UTC, AmanGuptAnalytics commented
Yes @TyDunn, its working. Thanx.

2023-03-29 15:17 UTC, AmanGuptAnalytics commented
In "Add credentials" there's a bit of incorrect numbering. Kindly see.

2023-03-30 13:06 UTC, TyDunn commented on docs/website/docs/pipelines/strapi.md
> +Strapi is a headless CMS (Content Management System), that allows developers to create powerful API-driven content management systems, without having to write a lot of custom code.
```suggestion
Strapi is a headless CMS (Content Management System) that allows developers to create powerful API-driven content management systems without having to write a lot of custom code.
```

2023-03-30 13:13 UTC, TyDunn commented
@AmanGuptAnalytics Can you please review / approve?

2023-03-30 16:25 UTC, AmanGuptAnalytics requested changes
Everything is perfect, you may ignore my comment, but I think it would look good. Like it did in pipedrive docs

2023-03-31 10:07 UTC, TyDunn commented on docs/website/docs/pipelines/strapi.md
> +1. Replace `"api_secret_key"` with the API token you copied above
Good idea! Adding this and then merging :)

2023-03-31 10:11 UTC, merged