prepare dataset release & docs updates
dlt-hub/dlt pull request #2126
Opened 2024-12-09 15:32 UTC by sh-rp

### Description
Makes dataset interface public and updates transformation and dataaccess snippets in docs to use this interface

2024-12-10 22:46 UTC, rudolfix approved these changes
OK, this is very good

2024-12-10 22:50 UTC, rudolfix requested changes
OK let's merge ibis first to see if docs will build again.

I'd show how to get data frame in https://dlthub.com/docs/intro "Python data structures" tab - to read content of the table as df

2024-12-11 19:17 UTC, rudolfix reviewed
LGTM. but let's wait for the final feedback

2024-12-13 12:16 UTC, AstrakhantsevaAA reviewed
Looks good! Suggest some small corrections

2024-12-13 12:27 UTC, AstrakhantsevaAA reviewed
noticed a typo

2024-12-13 12:27 UTC, AstrakhantsevaAA commented on docs/website/docs/intro.md
> +print(pipeline.dataset().foo_table.df())
```suggestion
print(pipeline.dataset().foo_data.df())
```

2024-12-15 16:16 UTC, merged