Added Hubspot setup guide
dlt-hub/dlt pull request #250
Opened 2023-04-12 03:02 UTC by AmanGuptAnalytics

Added setup guide for Hubspot, Please review @adrianbr & @TyDunn .

2023-04-12 14:19 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +---
```suggestion
---

```

2023-04-12 14:19 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +---
@rahuljo adding a space here

2023-04-12 14:19 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +The `dlt` HubSpot pipeline allows you to automatically load data from HubSpot onto a [destination](https://dlthub.com/docs/destinations) of your choice. It loads data from the following endpoints:
```suggestion
The `dlt` HubSpot pipeline allows you to automatically load data from HubSpot into a [destination](https://dlthub.com/docs/destinations) of your choice. It loads data from the following endpoints:
```

2023-04-12 14:20 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +```
```suggestion
:::info
```

2023-04-12 14:21 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +```
@AmanGuptAnalytics @rahuljo we should use [Admonitions](https://docusaurus.io/docs/markdown-features/admonitions) for things like this

2023-04-12 14:21 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +```
```suggestion
:::
```

2023-04-12 14:21 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +**Please note:**
```suggestion
```

2023-04-12 14:22 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +:::info
```suggestion
:::note
```

2023-04-12 14:22 UTC, TyDunn commented on docs/website/docs/pipelines/Hubspot.md
> +
```suggestion
```

2023-04-12 14:23 UTC, TyDunn requested changes
@rahuljo This should only include the Hubspot pipeline. For some reason, the Zendesk files are in here too

2023-04-12 14:39 UTC, rahuljo submitted a review, later dismissed

2023-04-12 15:10 UTC, TyDunn commented
@rahuljo why did you accept? are you fixing this problem?

2023-04-12 16:14 UTC, TyDunn approved these changes
LGTM!!

2023-04-13 07:01 UTC, TyDunn approved these changes

2023-04-13 07:01 UTC, merged