Add AirflowSecretsTomlProvider
dlt-hub/dlt pull request #273
Opened 2023-04-14 19:20 UTC by burnash

2023-04-16 06:31 UTC, rudolfix reviewed
Looks good! what we need are tests. you can take a look at #190 it seems that we need to add airflow to our dev dependencies and then you can just add this variable to in-memory metadata database https://stackoverflow.com/questions/69289343/can-you-create-a-variable-directly-in-an-airflow-dag

so it should be trivial

2023-04-20 15:18 UTC, burnash commented
@rudolfix the tests pass now with the updated poetry.lock. So it's ready for review.

2023-04-20 15:29 UTC, burnash commented on dlt/common/configuration/specs/config_providers_context.py
> +        providers += _extra_providers()
@rudolfix I wanted to decouple airflow provider from ConfigProvidersContext in a simples way possible. 
Later, if needed, we can implement this with a proper plugin-based architecture.

2023-04-20 16:10 UTC, rudolfix requested changes
@burnash just one small question to the workflow cache. otherwise it looks excellent. thanks for all the tests!

2023-04-20 16:16 UTC, burnash commented on .github/workflows/test_airflow.yml
> +          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-dbt-runner
Fixed

2023-04-21 08:53 UTC, rudolfix approved these changes

2023-04-21 10:41 UTC, merged