Docs: deploy airflow
dlt-hub/dlt pull request #410
Opened 2023-06-14 14:46 UTC by AstrakhantsevaAA

created folder deploy-a-pipeline, moved in there deploy github and airflow as separated pages.

2023-06-14 15:53 UTC, adrianbr requested changes

2023-06-14 15:53 UTC, adrianbr commented on docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-airflow-composer.md
> +Before you can deploy a pipeline, you will need to [install dlt](../../reference/installation.mdx) and [create a pipeline](../create-a-pipeline.md),
dot not comma at the end

2023-06-15 07:22 UTC, adrianbr approved these changes

2023-06-15 07:59 UTC, rudolfix approved these changes
ok this looks like quality! thanks for fixing all the relevant links also in the code!

2023-06-15 07:59 UTC, rudolfix commented on dlt/cli/deploy_command.py
> +DLT_DEPLOY_DOCS_URL = "https://dlthub.com/docs/walkthroughs/deploy-a-pipeline/deploy-with-github-actions"
we should have a corresponding link in our code for composer. I'll take a look in the other PR (#401 )

2023-06-15 07:59 UTC, rudolfix commented on docs/website/docs/reference/command-line-interface.md
>  [Google Composer](../running-in-production/orchestrators/airflow-gcp-cloud-composer.md) is a managed Airflow deployment provided by Google.
we should link IMO to your new docs page

2023-06-15 07:59 UTC, merged