Docs/user guide data scientists
dlt-hub/dlt pull request #436
Opened 2023-06-20 12:09 UTC by AstrakhantsevaAA

2023-06-20 14:12 UTC, adrianbr requested changes

2023-06-20 14:12 UTC, adrianbr commented on docs/website/docs/user-guides/data-scientist.md
> +- [Deploy this pipeline](../walkthroughs/deploy-a-pipeline), so that the data
deploy "the"/"that" pipeline ("this" makes me think there is a pipeline under the link)

2023-06-20 14:12 UTC, adrianbr commented on docs/website/docs/user-guides/data-scientist.md
> +separate, filter or transform sensitive data.
remove comma in "before loading data, allows us to separate" - alternatively, we need to add subject and verb for the preceding sentence ("dlt has the ability...")

2023-06-20 14:12 UTC, adrianbr commented on docs/website/docs/user-guides/data-scientist.md
> +cloud function or a lambda+ gateway could process events as they come.
or a lambda+ gateway -> "or an AWS Lambda and Api Gateway"

2023-06-20 14:12 UTC, adrianbr commented on docs/website/docs/user-guides/data-scientist.md
> +To use `dlt` for streaming cases effectively, it’s a good idea to microbatch your data before
move this paragraph above the small/large scale ones, or remove it

2023-06-21 12:40 UTC, rudolfix reviewed
this is almost good! my understanding of data scientist persosna is that we should offer practical solutions and link a lot to code and walkthroughs. this is not someone picking an architecture for data platform bur rather doing pip install in a notebook

2023-06-21 12:40 UTC, rudolfix commented on docs/website/docs/user-guides/data-scientist.md
> +- Use existed Verified Sources and pipeline examples or create your own quickly. See how to
please link add-a-pipeline here

2023-06-21 12:40 UTC, rudolfix commented on docs/website/docs/user-guides/data-scientist.md
> +- In addition to Streamlit, `dlt` natively supports
there's share-a-dataset where we explain how to go from local to bigquery. maybe we should link it?

2023-06-21 12:40 UTC, rudolfix commented on docs/website/docs/user-guides/data-scientist.md
> +## Use case #4: Real-time Data Streaming
my take - remove that section until we have a PoC. eventually we can link to our cloud function guide but still remove parts where we just theorize.

2023-06-21 13:57 UTC, adrianbr approved these changes

2023-06-21 14:03 UTC, merged