Added filesystem destination docs
dlt-hub/dlt pull request #440
Opened 2023-06-21 08:24 UTC by dat-a-man

2023-06-21 09:27 UTC, dat-a-man commented
@rudolfix , please verify if the permissions to read/write to s3 are correctly mentioned in the docs. I referred to this documentation: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_rw-bucket.html 
But seems not to work till now. Yesterday also it took a few hours then started loading to bucket using s3fullaccess. This time I am trying a custom aws IAM policy

2023-06-21 14:32 UTC, AstrakhantsevaAA commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +This command will initialise your pipeline with chess as the source and the AWS S3 filesystem as the destination.
add tabulation, 
```
1. To load the data to the AWS S3 file system, you must first initialise the project as follows:

    dlt init chess filesystem


    This command will initialise your pipeline with chess as the source and the AWS S3 filesystem as the destination.
```

2023-06-21 14:32 UTC, AstrakhantsevaAA commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +### Grab `credentials`
no need to highlight 'credentials' word

2023-06-21 14:32 UTC, AstrakhantsevaAA commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +4. Add the following roles to the policy, or you can also generate your policy using [AWS policy generator](https://awspolicygen.s3.amazonaws.com/policygen.html)
dot at the end

2023-06-21 14:32 UTC, AstrakhantsevaAA commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +To grab the credentials required you need to create a S3 bucket and a user who can access that bucket using certain permissions/policies.
To grab the required credentials

2023-06-22 08:18 UTC, dat-a-man commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +This command will initialise your pipeline with chess as the source and the AWS S3 filesystem as the destination.
done

2023-06-22 08:19 UTC, dat-a-man commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +### Grab `credentials`
done

2023-06-22 08:19 UTC, dat-a-man commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +4. Add the following roles to the policy, or you can also generate your policy using [AWS policy generator](https://awspolicygen.s3.amazonaws.com/policygen.html)
done

2023-06-22 08:19 UTC, dat-a-man commented on docs/website/docs/dlt-ecosystem/destinations/filesystem.md
> +To grab the credentials required you need to create a S3 bucket and a user who can access that bucket using certain permissions/policies.
done

2023-06-23 10:23 UTC, rudolfix requested changes
this is missing a explanation of the file layout in the bucket and how write disposition works. this is not issue with @dat-a-man contribution. I think we need to add some depth to all our destinations on top of a walkthrough

I'll add some details here

2023-06-23 14:37 UTC, dat-a-man commented
> this is missing a explanation of the file layout in the bucket and how write disposition works. this is not issue with @dat-a-man contribution. I think we need to add some depth to all our destinations on top of a walkthrough
> 
> I'll add some details here

Thanks @rudolfix and if you could please add some details here, I'll try updating all the other destinations with similar details 👍

2023-06-23 15:21 UTC, rudolfix commented
@dat-a-man thanks! I rewrote a large chunk of the doc. why did you need ACL permissions to load data? only basic permissions are needed

2023-06-23 16:18 UTC, dat-a-man commented
Thankyou @rudolfix and I'll fix that , I totally referred to the aws docs for s3 read/write policy mentioned in docs, will try again without acl permissions and update the docs :))

2023-06-23 16:31 UTC, merged