Fix/requests error handling
dlt-hub/dlt pull request #477
Opened 2023-07-07 00:36 UTC by steinitzu

Fixes https://github.com/dlt-hub/dlt/issues/473

* `ChunkedLoadingException` added to retry list. Seems this almost always due to some kind of dropped connection  
* requests `Timeout` and `ConnectionError` are already retried and all server errors inherit those
* Added some of the retry settings to `RunConfiguration`

2023-07-07 00:39 UTC, steinitzu commented on dlt/common/configuration/specs/run_configuration.py
> +    request_timeout: float = 60
Changed the type to float since union isn't supported in config, and thinking more common to use one number than the "connect, read" tuple.

2023-07-07 12:09 UTC, rudolfix requested changes
looks excellent! +1 for removing the tuples. pls. see one proposed improvement in the review.
what is missing is a short explanation how the timeout and retries are configured. please add a new section to `performance.md` in the docs - give an example how to configure retries and what are the defaults

2023-07-07 21:54 UTC, steinitzu commented on dlt/sources/helpers/requests/retry.py
>      def __init__(
Makes sense. Added this and some docs!

2023-07-08 15:54 UTC, rudolfix approved these changes

2023-07-08 15:55 UTC, merged