snippets prototype
dlt-hub/dlt pull request #559
Opened 2023-08-15 17:00 UTC by sh-rp

2023-08-18 11:16 UTC, rudolfix requested changes
this is really good. thanks for taking this task :)

now we need to decouple snippet tests and linting from the core CI. (maybe it is time to move docosaurus out?)
* we want the docs changes to run quickly on CI - like we do it now
* we should have separate linting and testing workflow for snippets and examples. it should run only if anything in docs changed!
* let's keep them in docs folder to make them isolated

2023-08-21 10:08 UTC, AstrakhantsevaAA commented on docs/website/docs/intro.md
> +    print(info)
can you delete extra tabs? it looks weird now(
![Снимок экрана 2023-08-21 в 12 07 13](https://github.com/dlt-hub/dlt/assets/20367975/103db09d-e63c-4eec-9f95-65d5ff1d1850)

2023-08-21 10:08 UTC, AstrakhantsevaAA commented on docs/website/docs/intro.md
> +    print(info)
before:
![Снимок экрана 2023-08-21 в 12 08 06](https://github.com/dlt-hub/dlt/assets/20367975/ba4ef832-a5cb-4ca1-9acf-a6dd57d9cd3e)

2023-08-21 12:53 UTC, sh-rp commented on docs/website/docs/intro.md
> +    print(info)
please see the comments about this on slack

2023-08-23 13:08 UTC, rudolfix approved these changes
heh `exec` worker. Python is scary :)

2023-08-23 13:17 UTC, rudolfix requested changes

2023-08-23 13:17 UTC, rudolfix commented on docs/snippets/utils.py
> +    exec(open(f"{BASEPATH}/{filename}.py", encoding="utf-8").read(), variables)
change the working dir to base path and use os.path.join to merge paths

2023-08-23 13:21 UTC, rudolfix commented on docs/snippets/intro_snippet_test.py
> +from docs.snippets.utils import run_snippet
add fixtures: preserve_environ, autouse_test_storage, patch_home_dir so the tests are isolated

2023-08-23 19:17 UTC, rudolfix approved these changes

2023-08-23 19:17 UTC, merged