NormalizerInfo: table counts trace
dlt-hub/dlt pull request #582
Opened 2023-08-24 11:36 UTC by sh-rp

2023-08-24 16:10 UTC, rudolfix approved these changes
this looks perfect!

2023-08-24 16:10 UTC, rudolfix commented on dlt/pipeline/pipeline.py
> +    def last_extract_info(self) -> ExtractInfo:
🙏

2023-08-24 18:41 UTC, rudolfix requested changes
we have normalize tests in `tests/normalize`. this is the only place where we test multi process normalization. so the only place that you will actually get counters across process boundary and merge them. please add tests there

2023-08-24 18:41 UTC, rudolfix commented on dlt/normalize/normalize.py
> +def merge_row_count(row_counts_1: TRowCount, row_counts_2: TRowCount) -> None:
actually you could move it common utils and give it 2-3 test cases?

2023-08-27 21:36 UTC, sh-rp commented
> we have normalize tests in `tests/normalize`. this is the only place where we test multi process normalization. so the only place that you will actually get counters across process boundary and merge them. please add tests there

I have added one that I think tests this, let me know if you think this is right.

2023-08-28 18:26 UTC, rudolfix requested changes
heh sorry I still have one issue :)

2023-08-28 18:26 UTC, rudolfix commented on dlt/pipeline/pipeline.py
> +    def last_pipeline_step_trace(self, step_name: TPipelineStep) -> PipelineStepTrace:
this is good. what I do not like it is that it should be a part of `PipelineTrace` class. we have plenty of methods and code in pipeline already and props below have nothing to do with pipeline itself...

2023-08-30 20:24 UTC, merged