Add pydantic support
dlt-hub/dlt pull request #589
Opened 2023-08-25 18:19 UTC by steinitzu

https://github.com/dlt-hub/dlt/issues/501

2023-08-26 11:55 UTC, rudolfix requested changes
thx for unifying the `columns` data type (we had both dicts and lists in different methods) and all the tests.

besides a few small comments in the review: could you add a short explanation to `resources.md` below `### Define schema` ie. `### Define schema with pydantic` where you can give an example and describe behavior (ie. lists, dics -> complex type/no child tables. optional - not null, unions - first element)

thanks!

2023-08-26 11:55 UTC, rudolfix commented on dlt/extract/decorators.py
> +    columns: TTableHintTemplate[TAnySchemaColumns] = None,
please type dlt.transformer below

2023-08-26 11:55 UTC, rudolfix commented on tests/extract/test_extract.py
> +from pydantic import BaseModel
do we need this?

2023-08-26 11:55 UTC, rudolfix commented on dlt/common/libs/pydantic.py
> +            "data_type": py_type_to_sc_type(inner_type),
👍

2023-08-26 11:55 UTC, rudolfix commented on dlt/common/libs/pydantic.py
> +        nullable = is_optional_type(annotation)
👍

2023-08-26 11:55 UTC, rudolfix commented on dlt/common/libs/pydantic.py
> +def pydantic_to_table_schema_columns(model: Union[BaseModel, Type[BaseModel]]) -> TTableSchemaColumns:
this is good. nullability is set and code to infer type reused :)

could we add one optional parameter: `skip_complex_types` default to False. if set we do not add columns with complex types at all to generated schema. that would mimic the default dlt behaviour that creates child tables.

2023-08-26 11:55 UTC, rudolfix commented on dlt/extract/utils.py
> +        def wrapper(item: TDataItem) -> TTableSchemaColumns:
forgot about that :) could you test it?

2023-08-27 20:50 UTC, steinitzu commented
Hey @rudolfix , added some docs, `skip_complex_types` and few more tests

2023-08-28 14:28 UTC, rudolfix approved these changes
excellent

2023-08-28 18:12 UTC, merged