Added Slack Docs!
dlt-hub/dlt pull request #643
Opened 2023-09-19 15:01 UTC by dat-a-man

### Description
Added Slack Docs!

### Related Issues

- Fixes #...
- Closes #...
- Resolves #...

### Additional Context

2023-09-26 11:55 UTC, sehnem requested changes

2023-09-26 11:55 UTC, sehnem commented on docs/website/docs/dlt-ecosystem/verified-sources/slack.md
> +| get_messages_resource | Retrives all the messages for a given channel                              |
For getting the messages we use the selected channel name.

2023-09-26 11:55 UTC, sehnem commented on docs/website/docs/dlt-ecosystem/verified-sources/slack.md
> +
The users resource is in review and should be merged soon, I think you can add it too.

2023-09-26 11:55 UTC, sehnem commented on docs/website/docs/dlt-ecosystem/verified-sources/slack.md
> +    yield from channel
I think that if you are adding this you should add the lines above it, as the `channel` variable is defined above, but I am not sure about it.

2023-09-29 15:29 UTC, AstrakhantsevaAA approved these changes

2023-09-29 15:29 UTC, merged