Adding the dlt dagster blog.
dlt-hub/dlt pull request #730
Opened 2023-11-01 13:29 UTC by zem360

Adding the dlt dagster blog post.

2023-11-07 11:22 UTC, AstrakhantsevaAA requested changes
Hi Zaeem! 
Great article! I have no comments on the content, only comments on the writing style. I’m sure this will help make the article more neat and enjoyable to read.

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +Initially, we will start by creating a simple data pipeline using `dlt`.  We will then orchestrate the pipeline using dagster. Finally, we will add more features to this pipeline by using the dlt sch
capitalize Dagster. somewhere you have it with a capital letter, somewhere with a small letter. maintain a consistent writing style throughout the text

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +The above code creates a simple github_issues pipeline that gets the issues data from the defined repository and loads it into BigQuery. The `dlt.resources` yields the data while the `dlt.pipeline` n
here makes sense to make **github_issues** bold

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +### Step 2: Set up the directory Structure
Structure word can be written in small letters :D

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +- Copy the previously created **`github_issues_resource`** code into **`dlt/__init__.py`** under the **`dlt`** folder. Remove the **`dlt.secrets.value`** parameter, as we'll pass the credentials thro
here to many unnecessary in bold words, as you can see in this paragraph **`.env`** is in bold, in the next one `.env` is not.

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +- Create a `.env` file in the root directory. This is the directory where the `pyproject.toml` file exits. Copy the credentials into the `.env` and follow the correct naming convention. For more info
(https://dlthub.com/docs/general-usage/credentials#reading-credentials-from-environment-variables). this link is not valid anymore, it leads to credentials section only

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +### Step 7: Run the Web Server and Materialize the asset
is this a gpt style? :D capitalize words if it's really necessary, e.g. Materialize could be written as materialize, this is not a proper name

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +The **github_issues** is the parent table that contains the data from the root level of the JSON returned by the GitHub API. The subsequent table **github_issues_assignees** is a child table that was
decide whether you highlight `dlt` everywhere or don’t highlight dlt everywhere

2023-11-07 11:22 UTC, AstrakhantsevaAA commented on docs/website/blog/2023-11-01-dlt-dagster.md
> +Dagster provides the feature of `**@multi_asset`** declaration that will allow us to convert each collection under a database into a separate asset. This will make our pipeline easy to debug in case
Here and further there is a conflict between quotation marks and asterisks `**@multi_asset`**. Always read the article carefully before publishing using the preview deploy. if you don't know how to do that let me know

2023-11-08 15:41 UTC, adrianbr approved these changes

2023-11-08 16:16 UTC, AstrakhantsevaAA approved these changes

2023-11-08 16:23 UTC, merged