Set port correctly in mssql connection string
dlt-hub/dlt pull request #731
Opened 2023-11-01 16:53 UTC by steinitzu

Resolves https://github.com/dlt-hub/dlt/issues/721

Fixes odbc connection string to use `SERVER=hostname,port` instead of `SERVER=hostname;PORT=port`

2023-11-06 11:28 UTC, rudolfix requested changes
fix is good! but arrow test is flaky. IMO
```
rows = [list(row) for row in select_data(pipeline, f"SELECT * FROM {qual_name} ORDER BY 1")]
```
you order by `_dlt_id` which is first AFAIK in the table, then
```
expected = sorted([list(r.values()) for r in records], key=lambda x: x[0])
```
you order by first data element (of string type)

and later it works if you are lucky :)

2023-11-06 16:23 UTC, steinitzu commented
> fix is good! but arrow test is flaky. IMO
> 
> ```
> rows = [list(row) for row in select_data(pipeline, f"SELECT * FROM {qual_name} ORDER BY 1")]
> ```
> 
> you order by `_dlt_id` which is first AFAIK in the table, then
> 
> ```
> expected = sorted([list(r.values()) for r in records], key=lambda x: x[0])
> ```
> 
> you order by first data element (of string type)
> 
> and later it works if you are lucky :)

True, I missed that. :grimacing:   
Will make this deterministic.

2023-11-08 11:51 UTC, rudolfix approved these changes
LGTM

2023-11-08 11:51 UTC, merged

2023-11-09 15:25 UTC, steinitzu commented on tests/load/mssql/test_mssql_credentials.py
> +        'DRIVER': 'ODBC Driver 18 for SQL Server',
Good catch, that's true it would fail.  
The test should specify the driver or ignore it in the assert.

2023-11-15 14:25 UTC, JonasDavisFondene commented
Is this not included in any release yet?
I see this merged into devel and version = "0.3.24" in devel pyproject.toml, but when I install 0.3.24 the credentials file is not updated, and I cant find #731 in any release here: https://github.com/dlt-hub/dlt/releases

2023-11-16 09:39 UTC, rudolfix commented
@JonasDavisFondene it is not yet included. we still prepare this week's release. we tag the commits with version number so you can see if the PR was merged before or after certain tag. this is not visible in commit history but in the release you can click on the tag and see what got included. not user friendly though...

2023-11-21 09:34 UTC, JonasDavisFondene commented
apart from the Driver 18 test independency suggestion, it would also be nice with some case insensitivity for parameter keys passed when using connection strings instead of secret.toml:
https://github.com/dlt-hub/dlt/compare/master...JonasDavisFondene:dlt:patch-2