Copy improvements in the SQL Database verified source
dlt-hub/dlt pull request #749
Opened 2023-11-10 19:16 UTC by anuunchin

### Description
Included the info asked in the issue.
Made some additional wording improvements in the docs on the SQL Database verified source. 

### Related Issues

- Partly resolves #720.

### Additional Context

This is a draft.

2023-11-10 20:16 UTC, rudolfix reviewed
LGTM! thanks for fixing spelling errors, I'll let @burnash to do a final review before we merge

2023-11-13 13:49 UTC, burnash requested changes
Hey @anuunchin thanks for great work! I've gone through your changes and overall, it's shaping up really well. There are a few minor adjustments I've suggested in the comments which I believe could make this page even better. Keep up the great work!

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +# +30 SQL Databases
```suggestion
# 30+ SQL Databases
```

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +> View the pipeline example
I suggest using a tip [admonition](https://docusaurus.io/docs/markdown-features/admonitions) instead of the markdown blockquote.

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +> Note that there many unofficial dialects, such as [DuckDB](https://duckdb.org/).
Same here: it's a good place to use a note [admonition](https://docusaurus.io/docs/markdown-features/admonitions) instead of the markdown blockquote.

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +> The database above doesn't require a password.
```suggestion
The database above doesn't require a password.
```

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +   > If you'd like to use a different destination, simply replace `duckdb` with the name of your preferred [destination](../destinations).
That's also a good place to use a tip admonition.

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +   > The pipeline_name for the above example is `rfam`, you may also use any
It's best to either remove a blockquote or use a "note" admonition here.

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +   > In this example, we load data from the 'family' table, using the 'updated' column for incremental loading. In the first run, the process loads all data starting from midnight (00:00:00) on Janua
```suggestion
   In this example, we load data from the `family` table, using the `updated` column for incremental loading. In the first run, the process loads all data starting from midnight (00:00:00) on January 1, 2022. Subsequent runs perform incremental loading, guided by the values in the `updated` field.
```

2023-11-13 13:49 UTC, burnash commented on docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
> +   > This process initially loads all data from the "family" table starting at midnight on January 1, 2022. For later runs, it uses the "updated" field for incremental loading as well.
```suggestion
   This process initially loads all data from the `family` table starting at midnight on January 1, 2022. For later runs, it uses the `updated` field for incremental loading as well. 
```

2023-11-16 17:32 UTC, burnash approved these changes
Thank you @anuunchin for the contribution. I appreciate the attention to details. Great work!

2023-11-16 17:40 UTC, merged