fix documentation typos
dlt-hub/dlt pull request #820
Opened 2023-12-12 04:32 UTC by IlyaFaer

2023-12-12 04:38 UTC, IlyaFaer commented
@rudolfix

2023-12-12 09:35 UTC, burnash approved these changes
Thanks for spotting this, @IlyaFaer

2023-12-12 12:51 UTC, rudolfix requested changes
thx for the fixes and for the review!
the tests for docs examples are not passing. the reason is that @IlyaFaer submitted PR from his fork of dlt and in that case, github actions do not have access to the secrets

I think I already asked to mark mongo tests to not run on fork

@IlyaFaer please do the above :) you can find a @skipifgithubfork decorator and mark the failing tests

in case they are already marked we need to fix the decorator. I know there were some problems with it

thanks :)

2023-12-13 08:23 UTC, IlyaFaer commented on .github/workflows/test_doc_snippets.yml
> +  IS_FORK: ${{ github.event.pull_request.head.repo.fork }}
This var is intended for forks detection, so it's functionality is guaranteed

2023-12-13 08:26 UTC, IlyaFaer commented on tests/utils.py
> -    return is_github_actions and ":" in head_ref and not head_ref.startswith(repo.split("/")[0])
These variables are not very reliable (like any paths on GitHub):

![image](https://github.com/dlt-hub/dlt/assets/26030071/121b3c55-5e56-4bdd-9989-b86ac4b6e998)

2023-12-13 09:39 UTC, rudolfix requested changes
I like it!
Please add comments both to the decorator and to the workflow yaml that explain how they work together - that you need to explicitly define the variable in order for it to work

then I'm good with it and we can merge

2023-12-13 09:58 UTC, IlyaFaer commented
@rudolfix, okay, pushed

2023-12-13 14:20 UTC, rudolfix approved these changes
LGTM!

2023-12-13 14:20 UTC, merged