787 - add missing tests
dlt-hub/dlt pull request #896
Opened 2024-01-16 11:03 UTC by sh-rp

### Description

### Related Issues

- Fixes #...
- Closes #...
- Resolves #...

### Additional Context

2024-01-17 14:16 UTC, sh-rp commented
@rudolfix what exactly needs to be tested on the pydantic nested models?

2024-04-17 23:08 UTC, rudolfix requested changes
LGTM! 2 tests need upgrade after few months of work

2024-04-17 23:08 UTC, rudolfix commented on tests/libs/pyarrow/test_pyarrow_normalizer.py
> +    columns = [new_column("_dlt_something", "bigint"), new_column("col2", "text")]
because of SCD2 only _dlt_versions and loads are removed. other columns may be added. check the normalize and pls fix the test

2024-04-17 23:08 UTC, rudolfix commented on tests/normalize/test_normalize.py
> +def test_removal_of_normalizer_schema_section(raw_normalize: Normalize) -> None:
so this test must be a little extended.
1. we remove evolove-columns-once
2. but we add `seen-data` to all tables that had data items (see shcema utils: has_table_seen_data)
this is a good test, needs to be upgraded

2024-04-24 11:31 UTC, rudolfix approved these changes
LGTM!

2024-04-24 13:19 UTC, merged