first draft of cli commands
dlt-hub/dlt pull request #98
Opened 2022-11-24 13:33 UTC by TyDunn

2022-11-30 14:13 UTC, rudolfix requested changes

2022-11-30 14:13 UTC, rudolfix commented on docs/website/docs/command-line-interface.md
> +dlt deploy <script>.py github-action --schedule * * * * *
the schedule part must be enclosed in quotation marks `"*/30 * * * *"`

2022-11-30 14:13 UTC, rudolfix commented on docs/website/docs/command-line-interface.md
> +dlt deploy <script>.py github-action --schedule * * * * *
t would be good to provide a working example

2022-11-30 14:13 UTC, rudolfix commented on docs/website/docs/command-line-interface.md
> +dlt init <source> <destination>
t would be good to provide a working example

2022-11-30 14:13 UTC, rudolfix commented on docs/website/docs/command-line-interface.md
> +If you want to start from a [generic template](https://github.com/dlt-hub/python-dlt-init-template),
Following @TyDunn and @adrianbr suggestions we have two generic templates now
1. **debugging template** with `dlt init <source> <destination>` where the data loading code is commented out, instead you have debug prints and mock data returned so you can run the code right away without credentials setup and see how dlt builiding blocks work
2. **generic template** with ` --generic` with all the data loading code present. you need to implement the missing requests to REST apis and provide credentials to run the pipeline for the first time

@rudolfix change the help text in `dlt` to reflect the name of parameters used here

2022-11-30 14:13 UTC, rudolfix commented on docs/website/docs/command-line-interface.md
> +dlt deploy <script>.py github-action --schedule * * * * *
it is worth stressing that schedule **must** be in quotation marks/apostrophes!

2022-12-07 17:21 UTC, TyDunn commented
Merging for now. I'll fix outstanding comments in a new PR

2022-12-07 17:21 UTC, merged